apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: expense
spec:
  serviceRef:
    name: frontend
    port: 80
  targetGroupARN: {{ .Values.tgb.arn }}
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: sg-0bce2729d3604ba5a
        ports:
          - protocol: TCP
            port: 80